# staging

web2 ansible_ssh_host=127.0.0.1 ansible_ssh_port=2200 ansible_ssh_private_key_file=/home/missioncontrol451/Development/ansible_reference_env/.vagrant/machines/web2/virtualbox/private_key ansible_ssh_user=vagrant
web1 ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=/home/missioncontrol451/Development/ansible_reference_env/.vagrant/machines/web1/virtualbox/private_key ansible_ssh_user=vagrant
db2 ansible_ssh_host=127.0.0.1 ansible_ssh_port=2202 ansible_ssh_private_key_file=/home/missioncontrol451/Development/ansible_reference_env/.vagrant/machines/db2/virtualbox/private_key ansible_ssh_user=vagrant
ci ansible_ssh_host=127.0.0.1 ansible_ssh_port=2203 ansible_ssh_private_key_file=/home/missioncontrol451/Development/ansible_reference_env/.vagrant/machines/ci/virtualbox/private_key ansible_ssh_user=vagrant
db1 ansible_ssh_host=127.0.0.1 ansible_ssh_port=2201 ansible_ssh_private_key_file=/home/missioncontrol451/Development/ansible_reference_env/.vagrant/machines/db1/virtualbox/private_key ansible_ssh_user=vagrant

[webtier]
web1
web2

[dbtier]
db1
db2

[monitoring]
ci
